name: UDMI Test Suite

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 13 * * *'

concurrency:
  group: ci-${{ github.repository }}
  cancel-in-progress: true

jobs:
  discoverynode:
    name: Discovery Node
    if: ${{ !cancelled() && vars.TARGET_PROJECT != '' }}
    env:
      TARGET_PROJECT: ${{ vars.TARGET_PROJECT }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: base setup
        run: |
          bin/setup_base
          bin/clone_model
      - name: integration test
        run: |
          misc/discoverynode/testing/e2e/test.sh $TARGET_PROJECT
